### ISSUE TITLE
where are the cookies stored

### ISSUE THREAD

**Issue by chrcoluk** [candh/cookies-backup-chrome#2]
I click on backup all cookies, type a password, hit enter and it says it saved all the cookies, but no idea where what folder they stored in.

Also its not obvious have to hit enter, perhaps should be a start button or something, I really hope you can reply as this is the only extension I found which can backup the cookies and restore.

**Comment by candh** [comment]
@chrcoluk they should be stored in your default download location

for more control, you can enable this option in the settings
![image](https://user-images.githubusercontent.com/11281452/145963854-e28c55a0-4692-4454-8b5e-59faada0ff63.png)
