### ISSUE TITLE
The extention's popup window closes too soon.

### ISSUE THREAD

**Issue by zachvlat** [candh/cookies-backup-chrome#5]
So, the extension works flawlessly so far, but when I tried to use it on Brave (stable) in Manjaro Linux, when I restore a cookie file, it should prompt me to type the password underneath it. But, when I choose my file, the extension's windows immediately closes and I am unable to type the cookie's password. Maybe the window should not close if the password is not set.

**Comment by zachvlat** [comment]
One solution for this issue is to delete the <script src="popup.js"></script> tag (when I open the extension window) just to make it work for Linux (this also happens on Pop_OS and Elementary OS).

**Comment by candh** [comment]
@zachvlat thanks for reporting and the follow up tip! really appreciate it.

I _think_ this is a Linux windowing system issue. I haven't tested this on any linux distro at all. I'll try to recreate and try to fix.

**Comment by zachvlat** [comment]
you can put a user agent if its linux or smth hide this tag... I don't know how it ll affect the rest of the extension though, but it worked for me!

**Comment by candh** [comment]
@zachvlat i was able to recreate this problem. 

but can you clarify what you mean by "deleting" the `script` tag? Do you mean programmatically removing this tag from the DOM?

How did you hide/delete the `script` tag in order to solve this? Did you remove it through the Inspect window?

**Comment by zachvlat** [comment]
Yes, I just remove the whole tag through the inspect window. Right click on Choose File button - > open inspect and then delete the element <script src="popup.js"></script>. Then without closing the inspect window, I choose my file and done.

**Comment by candh** [comment]
oh, well, the extension only remains open _only because_ [you have the inspect window open](https://stackoverflow.com/a/4148839/4441060)

i'm adding a "paste your .ckz file contents" thing which should solve this. let me know if you have any other ideas!

**Comment by zachvlat** [comment]
> oh, well, the extension only remains open _only because_ [you have the inspect window open](https://stackoverflow.com/a/4148839/4441060)
> 
> i'm adding a "paste your .ckz file contents" thing which should solve this. let me know if you have any other ideas!

lol, i didn't think about it! nice job

**Comment by candh** [comment]
resolved with new version
